apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-zcng
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-zcng
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-zcng
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-zcng
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-zcng
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/dc-metro-map-zcng@sha256:19093c7623252c0268c8fe706bac45dfc5e860161c20fd5c678d01ef99245335
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
